### ISSUE TITLE
TRAKTOR SCRATCH MK2 control vinyl

### ISSUE THREAD

**Issue by imbmf** [jrosener/digitalscratch#116]
Hello,
can I use TRAKTOR SCRATCH MK2 control vinyl?
Thank you!

**Comment by jrosener** [comment]
Hello,

Unfortunately I don't have a pair of TRAKTOR SCRATCH MK2 vinyls. But it is probably closed to FINAL SCRATCH vinyls. If you can send me a record as mp3 or wav (only a part should be sufficient) of your control vinyl, I think it should feasible to support it.

Julien.
