### ISSUE TITLE
Will there be an updated version of digitalscratch (and related packages like keyfinder) for the newer Ubuntus?

### ISSUE THREAD

**Issue by Weej1** [jrosener/digitalscratch#117]
Hi ! 
I actually found your mix on soundcloud and then followed the vimeo video to your site. Was ecstatic to find this was available on my main OS (Ubuntu) albeit older versions of it. 

I've managed to install digital scratch and keyfinder from the version meant for 15.04 and was wondering if you'd ever do an update for 16.04 / 17.04 etc? 

Thanks so much for this software I never thought I could try this on linux!

**Comment by jrosener** [comment]
Hi !

Thank you for the support :)
I just saw that Ubuntu 17.04 was released last week. I will make packets for this release (even the current implementation contains unfinished features, but I am going very slowly :)). I will try to do it in the next days, just need to find a bit of time.

Julien.

**Comment by Weej1** [comment]
Thank you! I look forward to it.

**Comment by jrosener** [comment]
Ubuntu packages (digitalscratch 1.6.2 & libkeyfinder 2.2.1):
* 16.04 LTS packages (digitalscratch 1.6.2 & libkeyfinder 2.2.1): https://launchpad.net/~julien-rosener/+archive/ubuntu/digitalscratch/+packages?field.name_filter=&field.status_filter=published&field.series_filter=xenial
* 17.04: https://launchpad.net/~julien-rosener/+archive/ubuntu/digitalscratch/+packages?field.name_filter=&field.status_filter=published&field.series_filter=zesty
