### ISSUE TITLE
Support GUI internationalization

### ISSUE THREAD

**Issue by jrosener** [jrosener/digitalscratch#122]
- [x] Add internationalization support based on Qt framework and tools.
- [x] Translate GUI into french.

**Comment by jrosener** [comment]
Done in commit efa0582fd1ed3df9bd2fda475362ca1070ecbc27

How to support a new language ?

1. Duplicate changes done for french language:
   - reference a new translation file in digitalscratch.pro
     (translations/digitalscratch_xx.ts)
   - add the new language in application settings and config dialog

2. Create/update all translation files by scanning for "tr()" calls in
   source code:
   `$ lupdate -no-obsolete -verbose digitalscratch.pro`

3. Edit translation file one by one with Qt Linguist:
   `$ linguist translations/digitalscratch_fr.ts`

4. Convert all .ts files to .qm binaries:
   `$ lrelease digitalscratch.pro`

5. Rebuild and test.

**Comment by trebmuh** [comment]
:+1:
