### ISSUE TITLE
GUI in French

### ISSUE THREAD

**Issue by trebmuh** [jrosener/digitalscratch#131]
salut @jrosener 

j'ai bien le fichier digitalscratch_fr.qm présent avec des droits en lecture dessus pour tout le monde :
```
$ ls /usr/share/digitalscratch/translations/digitalscratch_fr.qm -la
-rw-r--r-- 1 root root 13646 nov.   8 22:46 /usr/share/digitalscratch/translations/digitalscratch_fr.qm
```
j'ai supprimé le fichier de configuration-utilisateur : `~/.config/digitalscratch.conf`.

Si je vais dans SETTINGS -> GUI language (restart required), que je sélectionne le FR, puis que je ferme et réouvre digitalscratch, l'interface est toujours en anglais.

Le plus bizarre, c'est que j'ai réussi une fois à avoir l'interface graphique utilisateur en français, mais que je n'y parviens plus.

Une idée ?

**Comment by jrosener** [comment]
Salut,

Problème reproduit : lors du chargement de `digitalscratch_fr.qm`, le chemin du fichier n'est pas bon. Comme ce n'est pas forcément évident d'avoir un chemin pour le mode de development et un autre pour le mode `release`, j'ai décidé d'integrer les fichiers `.qm` dans le binaire `digitalscratch` en tant que resource Qt. Le fix sera intégré dans la prochaine version.
J'imagine que ca a marché une fois chez toi parce que tu l'avais compilé toi même, et donc le chemin d'accès au fichier était le bon.

**Comment by trebmuh** [comment]
OK @jrosener j'ai refait un paquet en y ajoutant [ta rustine](https://github.com/jrosener/digitalscratch/commit/673d09bb2d4de1a973138bb9f717a918ccb9e6cc), et j'ai bien l'interface graphique en français à présent. Chouette !

**Comment by jrosener** [comment]
Nickel ! :)
